<a href="https://colab.research.google.com/github/Amarjeet-1998/keras_practice/blob/main/Keras_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [2]:
train_lables = []
train_samples = []

### Example data:


*   An experiment drug was tested on indivisuals from ages 13 to 65.
*   he trial had 2100 participants.Half were under 65 years old, half were over 65 years old
*   95% of patients 65 or older experienced side effects.
*   95% of patients under 65 experienced no side effects. 



In [3]:
import random
for i in range(1000):
  random_younger = randint(13,64)
  train_samples.append(random_younger)
  train_lables.append(0)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_lables.append(1)

for i in range(50):
  random_younger = randint(65,100)
  train_samples.append(random_younger)
  train_lables.append(1)

  random_older = randint(65,100)
  train_samples.append(random_older)
  train_lables.append(0)


In [4]:
#print row data
for i in train_samples:
  print(i)

36
100
61
78
19
82
24
92
14
98
24
79
20
92
45
95
27
79
27
100
20
97
22
90
40
82
30
74
64
68
32
71
37
86
29
96
63
99
26
100
15
94
29
91
27
96
47
96
14
69
45
100
59
97
51
81
24
82
41
66
48
67
43
73
29
90
49
70
14
89
61
69
57
94
43
79
42
86
53
65
16
86
58
79
23
89
61
95
42
72
46
91
28
67
51
70
19
100
43
70
48
91
63
71
15
84
53
70
14
75
60
98
62
79
57
69
37
99
19
99
13
97
26
78
64
91
24
91
19
76
24
74
33
85
60
99
33
70
24
93
57
98
33
81
51
96
55
86
56
91
23
67
46
99
31
94
39
86
47
86
40
70
21
100
20
100
56
90
57
68
57
95
31
81
36
99
48
68
50
95
58
76
36
98
14
69
38
78
50
87
16
86
52
75
14
92
28
98
31
88
38
92
14
90
57
73
39
92
43
97
63
92
20
91
42
78
18
92
63
96
35
92
32
84
27
69
50
69
36
94
13
97
22
72
45
79
50
100
39
80
28
75
29
70
17
90
36
73
41
67
58
72
57
77
29
98
62
95
54
91
18
86
19
88
61
87
56
92
34
100
60
91
45
84
36
98
37
89
31
95
34
98
13
82
51
73
39
73
55
80
48
98
33
84
62
86
34
69
62
83
52
77
34
94
47
80
43
86
26
91
26
83
17
72
59
81
25
94
46
90
40
93
21
98
48
97
32
68
35
72
3

In [5]:
#print row data
for i in train_lables:
  print(i)

0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1
0
1


In [6]:
train_lables = np.array(train_lables)
train_samples = np.array(train_samples)

In [7]:
train_lables

array([0, 1, 0, ..., 0, 1, 0])

In [8]:
train_samples

array([ 36, 100,  61, ...,  90,  89,  76])

In [9]:
scaler = MinMaxScaler(feature_range = (0,1))
scaled_train_samples = scaler.fit_transform((train_samples).reshape(-1,1))

In [10]:
scaled_train_samples

array([[0.26436782],
       [1.        ],
       [0.55172414],
       ...,
       [0.88505747],
       [0.87356322],
       [0.72413793]])

In [11]:
#print scaled data
for i in scaled_train_samples:
  print(i)

[0.26436782]
[1.]
[0.55172414]
[0.74712644]
[0.06896552]
[0.79310345]
[0.12643678]
[0.90804598]
[0.01149425]
[0.97701149]
[0.12643678]
[0.75862069]
[0.08045977]
[0.90804598]
[0.36781609]
[0.94252874]
[0.16091954]
[0.75862069]
[0.16091954]
[1.]
[0.08045977]
[0.96551724]
[0.10344828]
[0.88505747]
[0.31034483]
[0.79310345]
[0.1954023]
[0.70114943]
[0.5862069]
[0.63218391]
[0.2183908]
[0.66666667]
[0.27586207]
[0.83908046]
[0.18390805]
[0.95402299]
[0.57471264]
[0.98850575]
[0.14942529]
[1.]
[0.02298851]
[0.93103448]
[0.18390805]
[0.89655172]
[0.16091954]
[0.95402299]
[0.3908046]
[0.95402299]
[0.01149425]
[0.64367816]
[0.36781609]
[1.]
[0.52873563]
[0.96551724]
[0.43678161]
[0.7816092]
[0.12643678]
[0.79310345]
[0.32183908]
[0.6091954]
[0.40229885]
[0.62068966]
[0.34482759]
[0.68965517]
[0.18390805]
[0.88505747]
[0.4137931]
[0.65517241]
[0.01149425]
[0.87356322]
[0.55172414]
[0.64367816]
[0.50574713]
[0.93103448]
[0.34482759]
[0.75862069]
[0.33333333]
[0.83908046]
[0.45977011]
[0.59770115]